### ISSUE TITLE
Consider distributing with Homebrew

### ISSUE THREAD

**Issue by laughedelic** [utatti/kawa#15]
Right now downloading every new version as an archive from Github and unpacking it manually is quite inconvenient. And more importantly, many users won't even know that they can update.

As this is purely macOS software, it would make sense to use [Homebrew](https://brew.sh/) for installing it and updating. 

If you're not opposed to this idea, I can help with writing a Homebrew formula (on the weekend), it's quite easy.

**Comment by noraesae** [comment]
As it's not a command-line tool, I guess it would be Homebrew Cask, woudn't it?

I'm not particularly against the idea, but I may not maintain it by myself for the cost.

**Comment by laughedelic** [comment]
Right, I meant Homebrew Cask. 

Maintenance usually consist of just updating the version number in the formula and the link the the archive. So it's not hard. Anyway, I'll try it out on the weekend and tell you how it goes.

**Comment by rickeylau** [comment]
Please support Homebrew! New version is easy to download.

**Comment by laughedelic** [comment]
Finally got some time to do it. Check https://github.com/caskroom/homebrew-cask/pull/39665. Once it's merged, you should be able to install it with `brew cask install kawa` and then just use `brew update`/`brew upgrade kawa`.

**Comment by laughedelic** [comment]
@utatti @rickeylau good news! Cask PR got already merged, so now people can install Kawa with `brew cask install kawa`.

**Comment by utatti** [comment]
Great! Thanks very much 👍
