### ISSUE TITLE
Errors in repeated use

### ISSUE THREAD

**Issue by wokenshin** [utatti/kawa#18]
Shortcut key invalidation

**Comment by utatti** [comment]
Can I have more detailed information? What does it mean by 'key invalidation'?

**Comment by wokenshin** [comment]
Sorry，The shortcut key cannot be used

**Comment by utatti** [comment]
If 'repeated use' means inputting same shortcut in series while control keys are down, I guess it may be related with CJKV input source handling?

- https://github.com/utatti/kawa#for-cjkv-input-sources

Can you please check if it happens with non-CJKV inputs, such as U.S.?

**Comment by wokenshin** [comment]
Yes，I used Janpan input source and Chinese

**Comment by utatti** [comment]
Yes, it's a known issue of CJKV sources, to workaround macOS bug. Please input one shortcut per change.

**Comment by wokenshin** [comment]
thx very much
