### ISSUE TITLE
Notifications show up even when disabled

### ISSUE THREAD

**Issue by antonshevyrin** [utatti/kawa#20]
I still see notifications like this one when I switch language:
<img width="344" alt="kawa_notification" src="https://user-images.githubusercontent.com/807405/40914564-5a14481e-6801-11e8-919e-e3400c9cede4.png">

While notifications are disabled in Kawa settings:
<img width="400" alt="kawa_settings" src="https://user-images.githubusercontent.com/807405/40914565-5a2f5d0c-6801-11e8-9814-a3d8d445f140.png">

Kawa stable version 3.0 installed.
Mac OS High Sierra 10.13.4.

**Comment by machinemxy** [comment]
It was solved by check the checkbox and then uncheck it.

**Comment by antonshevyrin** [comment]
@machinemxy thanks, this solved problem for me too
